version: '3.7'
services:
  postgressql_database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=ibge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'